export const MESSAGE_LIST_REQUEST = "MESSAGE_LIST_REQUEST";
export const MESSAGE_LIST_SUCCESS = "MESSAGE_LIST_SUCCESS";
export const MESSAGE_LIST_FAILED = "MESSAGE_LIST_FAILED";
export const MESSAGE_LIST_RESET = "MESSAGE_LIST_RESET";

export const MESSAGE_CREATE_REQUEST = "MESSAGE_CREATE_REQUEST";
export const MESSAGE_CREATE_SUCCESS = "MESSAGE_CREATE_SUCCESS";
export const MESSAGE_CREATE_FAILED = "MESSAGE_CREATE_FAILED";
export const MESSAGE_CREATE_RESET = "MESSAGE_CREATE_RESET";
